/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/router';

import { CryptocurrencyData as CryptocurrencyData } from './components/cryptocurrency-data/cryptocurrency-data';

interface HTMLCryptocurrencyDataElement extends CryptocurrencyData, HTMLElement {
}
declare var HTMLCryptocurrencyDataElement: {
  prototype: HTMLCryptocurrencyDataElement;
  new (): HTMLCryptocurrencyDataElement;
};
declare global {
  interface HTMLElementTagNameMap {
      "cryptocurrency-data": HTMLCryptocurrencyDataElement;
  }
  interface ElementTagNameMap {
      "cryptocurrency-data": HTMLCryptocurrencyDataElement;
  }
  namespace JSX {
      interface IntrinsicElements {
          "cryptocurrency-data": JSXElements.CryptocurrencyDataAttributes;
      }
  }
  namespace JSXElements {
      export interface CryptocurrencyDataAttributes extends HTMLAttributes {
        
          coin?: any,
          show?: any
      }
  }
}

