/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface CryptocurrencyData {
    'coin': string;
    'show': string;
  }
  interface CryptocurrencyDataAttributes extends StencilHTMLAttributes {
    'coin'?: string;
    'onCcd_apiCalled'?: (event: CustomEvent) => void;
    'onCcd_coinData'?: (event: CustomEvent) => void;
    'show'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'CryptocurrencyData': Components.CryptocurrencyData;
  }

  interface StencilIntrinsicElements {
    'cryptocurrency-data': Components.CryptocurrencyDataAttributes;
  }


  interface HTMLCryptocurrencyDataElement extends Components.CryptocurrencyData, HTMLStencilElement {}
  var HTMLCryptocurrencyDataElement: {
    prototype: HTMLCryptocurrencyDataElement;
    new (): HTMLCryptocurrencyDataElement;
  };

  interface HTMLElementTagNameMap {
    'cryptocurrency-data': HTMLCryptocurrencyDataElement
  }

  interface ElementTagNameMap {
    'cryptocurrency-data': HTMLCryptocurrencyDataElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
